steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/literallyacheron-backend/AcheronBackEnd', '-f', 'AcheronBackEnd/AcheronBackEnd/Dockerfile', '.']
images:
  - 'gcr.io/$PROJECT_ID/acheronbackend'
options:
  logging: CLOUD_LOGGING_ONLY
